---
- name: Get ARP Information
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: ARPInformation
      ios_command:
        commands:
          - show arp
      register: print_output

    -  debug: var=print_output.stdout_lines

